#### general settings
name: OCTData1
use_tb_logger: false
model: OCTDegSRModel
scale: 4
gpu_ids: [0]
metrics: [niqe]

#### datasets
datasets:
  train:
    name: OCTX4
    mode: UnpairedOCTDataset
    data_type: lmdb
    color: Gray
    ratios: [200, 200]

    dataroot_tgt: D:/zhiyi/OCT_SR/OCT_data/Unpaired_dataset/resol_3d8_10.lmdb
    dataroot_src: D:/zhiyi/OCT_SR/OCT_data/Unpaired_dataset/resol_16_40.lmdb

    use_shuffle: true
    workers_per_gpu: 6  # per GPU
    imgs_per_gpu: 8
    tgt_size: 128
    src_size: 32
    use_flip: true
    use_rot: true

  val:
    name: OCT16_40_val
    mode: SingleOCTDataset
    data_type: lmdb
    color: Gray
    dataroot: D:/zhiyi/OCT_SR/OCT_data/Unpaired_dataset/resol_16_40_crop_val.lmdb

#### network structures
networks:
  netDeg:
    which_network: OCTDegModel
    setting:
      scale: 4
      nc_img: 1
      kernel_opt:
        spatial: true
        nc: 1
        nf: 64
        nb: 8
        head_k: 1
        body_k: 1
        ksize: 11
        zero_init: true
      noise_opt: 
        spatial: true
        nc: 1
        nf: 32
        nb: 8
        head_k: 3
        body_k: 3
        dim: 1
        zero_init: true
    pretrain: 
      path: ~
      strict_load: true

  netSR:
    which_network: EDSR
    setting:
      nf: 64
      nb: 16
      res_scale: 1
      upscale: 4
    pretrain: 
      path: ../../../checkpoints/EDSR/edsr_baseline_x4-new.pt
      strict_load: true
  
  netD1:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 1
      nf: 64
      nb: 3
      stride: 1
    pretrain: 
      path: ~
      strict_load: true

  netD2:
    which_network: PatchGANDiscriminator
    setting:
      in_c: 1
      nf: 64
      nb: 3
      stride: 1
    pretrain:
      path: ~
      strict_load: true
      
#### training settings: learning rate scheme, loss
train:
  resume_state: ~
  D_ratio: 1
  max_grad_norm: 50
  buffer_size: 0

  optim_deg: true
  optim_sr: true
  
  losses:

    sr_pix_sr: 
      type: L1Loss
      weight: 1.0
    
    noise_mean:
      type: MSELoss
      weight: 1.0
    
    lr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.05

    sr_adv:
      type: GANLoss
      gan_type: lsgan
      real_label_val: 1.0
      fake_label_val: 0.0
      weight: !!float 0.05
    
    sr_percep:
      type: PerceptualLoss
      layer_weights:
        'conv5_4': 1  # before relu
      vgg_type: vgg19
      use_input_norm: true
      range_norm: false
      perceptual_weight: 1.0
      style_weight: 0
      criterion: l1
      weight: !!float 0.05

  optimizers:
    default:
      type: Adam
      lr: !!float 2e-4
    netDeg: ~
    netSR: ~
    netD2: ~
    netD1: ~

  niter: 200000
  warmup_iter: -1  # no warm up

  schedulers:
    default:
      type: MultiStepRestartLR
      milestones: [50000, 100000, 150000]
      gamma: 0.5

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
